Merge with default (r744cb43bce5d831a84632e2b073dc8e0dddc1831)

diff --git a/ganttproject-builder/ganttproject b/ganttproject-builder/ganttproject
--- a/ganttproject-builder/ganttproject
+++ b/ganttproject-builder/ganttproject
@@ -1,47 +1,29 @@
 #!/bin/bash
 
-COMMAND_PATH=$(readlink -e "$0" | sed -e "s/\(.*\)\/.*$/\1/g")
-if [ ! -d $COMMAND_PATH ]; then
-  echo "Path '$COMMAND_PATH' does not exist"
-  exit 1
-fi
-GP_HOME=$(readlink -e "$COMMAND_PATH")
+SCRIPT_PATH=$0
+RESOLVED_PATH=`readlink "$SCRIPT_PATH"`
+while [ ! -z $RESOLVED_PATH ]; do
+  SCRIPT_PATH=$RESOLVED_PATH
+  RESOLVED_PATH=`readlink "$SCRIPT_PATH"`
+done
+GP_HOME=`dirname "$SCRIPT_PATH"`
 
-# Expand all filenames in arguments
-argstring=""
-if [ $# -gt 0 ]; then
-  for arg in "$@"; do
-    if [ -z "$(echo "$arg" | sed -n '/^-/p')" ]; then
-      fullargpath=$(readlink -f "$arg")
-      if [ -n "$fullargpath" ]; then
-        argstring="$argstring '$fullargpath'"
-      else
-        echo "Warning file: '$1' not found; Forgot to escape or quote spaces?"
-      fi
-    else
-      argstring="$argstring $arg";
-    fi
-  done
-  # Update arguments with $argstring if set
-  if [ -n "$argstring" ]; then
-    eval "set -- $argstring"
-  fi
-fi
 
-# Check if ~/.GanttProject/ is present (or create it)
-if [ ! -d ${HOME}/.GanttProject ]; then
-  if [ -e  ${HOME}/.GanttProject ]; then 
-    echo "file ${HOME}/.GanttProject is not a directory" >&2
+GP_LOG_DIR="$HOME/.ganttproject.d"
+# Check if log dir is present (or create it)
+if [ ! -d $GP_LOG_DIR ]; then
+  if [ -e  $GP_LOG_DIR ]; then
+    echo "file $GP_LOG_DIR exists and is not a directory" >&2
     exit 1
   fi
-  if ! mkdir ${HOME}/.GanttProject ; then
-    echo "Could not create ${HOME}/.GanttProject directory" >&2
-    exit 1 
+  if ! mkdir $GP_LOG_DIR ; then
+    echo "Could not create $GP_LOG_DIR directory" >&2
+    exit 1
   fi
 fi
 
 # Create unique name for log file
-LOG_FILE="${HOME}/.GanttProject/.ganttproject-"$(date +%Y%m%d%H%M%S)".log"
+LOG_FILE="$GP_LOG_DIR/.ganttproject-"$(date +%Y%m%d%H%M%S)".log"
 if [ -e "$LOG_FILE" ] && [ ! -w "$LOG_FILE" ]; then
   echo "Log file $LOG_FILE is not writable" >2
   exit 1
@@ -62,14 +44,13 @@ if [ ! -x "$JAVA_COMMAND" ]; then
   exit 1
 fi
 
-LOCAL_CLASSPATH=${GP_HOME}/eclipsito.jar:${GP_HOME}:${COMMAND_PATH}:${GP_HOME}/plugins:${COMMAND_PATH}/plugins
+LOCAL_CLASSPATH=${GP_HOME}/eclipsito.jar:${GP_HOME}
 CONFIGURATION_FILE=ganttproject-eclipsito-config.xml
 BOOT_CLASS=org.bardsoftware.eclipsito.Boot
 
-cd $COMMAND_PATH
-if [ -n "$(echo \"$*\" | sed -n '/\(^\|\s\)-/{p;}')" ]; then 
-  $JAVA_COMMAND -Xmx256m -classpath $CLASSPATH:$LOCAL_CLASSPATH $BOOT_CLASS $CONFIGURATION_FILE -log $LOG_FILE "$@"
+if [ -n "$(echo \"$*\" | sed -n '/\(^\|\s\)-/{p;}')" ]; then
+  $JAVA_COMMAND -Xmx256m -classpath $CLASSPATH:$LOCAL_CLASSPATH $BOOT_CLASS $CONFIGURATION_FILE -log -log_file $LOG_FILE "$@"
 else
-  exec $JAVA_COMMAND -Xmx256m -classpath $CLASSPATH:$LOCAL_CLASSPATH $BOOT_CLASS $CONFIGURATION_FILE -log $LOG_FILE "$@" &
+  exec $JAVA_COMMAND -Xmx256m -classpath $CLASSPATH:$LOCAL_CLASSPATH $BOOT_CLASS $CONFIGURATION_FILE -log -log_file $LOG_FILE "$@" &
 fi
 
