* No need to separate boot and app arguments with -- * Print the log on ERR or EXIT with code != 0 * Better handling of spaces in the paths * Do not run in background by default * macOS script also accepts all the arguments

diff --git a/ganttproject-builder/ganttproject b/ganttproject-builder/ganttproject
--- a/ganttproject-builder/ganttproject
+++ b/ganttproject-builder/ganttproject
@@ -5,6 +5,36 @@
 
 SCRIPT_FILE="$0"
 
+# If we can write to /tmp/ganttproject-launcher.log then LOG_TEXT
+# will be empty, and we'll write the launcher logs to the file
+# Otherwise it will be not empty and will accumulate the
+# logged information in memory.
+LOG_TEXT=""
+echo "" > /tmp/ganttproject-launcher.log || LOG_TEXT="----"
+
+log() {
+  if [ -n "$LOG_TEXT" ]; then
+    LOG_TEXT="$LOG_TEXT\n$1";
+  else
+    echo "$1" >> /tmp/ganttproject-launcher.log
+  fi
+  [ -z "$DEBUG_ARGS" ] || echo $1
+}
+
+trap 'print_log' ERR
+trap 'print_log' EXIT
+
+print_log() {
+  if [ "$?" -eq "0" ]; then
+    return;
+  fi
+  if [ -n "$LOG_TEXT" ]; then
+    >&2 echo "$LOG_TEXT"
+  else
+    >&2 cat /tmp/ganttproject-launcher.log
+  fi
+}
+
 find_ganttproject_home() {
   WORKING_DIR="$(pwd)"
   # We want to find the directory where the real script file resides.
@@ -31,47 +61,46 @@ fi
 # Parse the command line arguments. In this script we parse only those arguments which
 # are related to the Java VM launching. The remaining application-specific arguments
 # are passed as-is to the Java process.
-PARSED_ARGS=$(getopt -o d::j:: --long debug:: --long java-home:: -- "$@")
-eval set -- "$PARSED_ARGS"
 
 USE_BUNDLED_RUNTIME=1
 DEBUG_ARGS=""
+APP_ARGS=()
+
 while true; do
   case "$1" in
     # Debug will switch on some debugging output and will allow for connecting to Java
     # process with a debugger
     -d|--debug)
       case "$2" in
-        "")
-          DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
-          shift 2
-          ;;
-        *)
+        +[:digit:])
           DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=$2,suspend=n"
           shift 2
           ;;
+        *)
+          DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
+          shift 1
+          ;;
       esac
+      log "Debug arguments: $DEBUG_ARGS"
       ;;
     # This allows for specifying the path to Java Runtime instead of the default bundled Java Runtime
     -j|--java-home)
       USE_BUNDLED_RUNTIME=0
-      case "$2" in
-        "")
-          shift 2
-          ;;
-        *)
-          JAVA_HOME="$2"
-          shift 2
-          ;;
-       esac
-       ;;
-    --)
-      shift
-      break
+      if [ -d "$2" ]; then
+        JAVA_HOME="$2"
+        log "Using JAVA_HOME=$2"
+        shift 2
+      else
+        log "This is not a directory: $2"
+        exit 1
+      fi
+      ;;
+    "")
+      break;
       ;;
     *)
-      echo "Unexpected argument $1"
-      exit 1
+      APP_ARGS+=("$1")
+      shift 1
       ;;
   esac
 done
@@ -97,22 +126,6 @@ if [ -e "$LOG_FILE" ] && [ ! -w "$LOG_FILE" ]; then
   exit 1
 fi
 
-# If we can write to /tmp/ganttproject-launcher.log then LOG_TEXT
-# will be empty, and we'll write the launcher logs to the file
-# Otherwise it will be not empty and will accumulate the
-# logged information in memory.
-LOG_TEXT=""
-echo "" > /tmp/ganttproject-launcher.log || LOG_TEXT="----"
-
-log() {
-  if [ ! -z "$LOG_TEXT" ]; then
-    LOG_TEXT="$LOG_TEXT\n$1";
-  else
-    echo $1 >> /tmp/ganttproject-launcher.log
-  fi
-  [ -z "$DEBUG_ARGS" ] || echo $1
-}
-
 # This function checks if the passed argument is a good java command.
 # It is expected to be executable and expected to return version 11+ when launched with -version
 # argument.
@@ -128,14 +141,14 @@ check_java() {
 
   VERSION="$( $JAVA_COMMAND -version 2>&1 | grep version | head -n 1)"
   log "...found $VERSION"
-  [[ "$VERSION" =~ "11." ]] && return 0;
-  [[ "$VERSION" =~ "12." ]] && return 0;
-  [[ "$VERSION" =~ "13." ]] && return 0;
-  [[ "$VERSION" =~ "14." ]] && return 0;
-  [[ "$VERSION" =~ "15." ]] && return 0;
-  [[ "$VERSION" =~ "16" ]] && return 0;
-  [[ "$VERSION" =~ "17" ]] && return 0;
-   log "...this seems to be an old Java Runtime";
+  [[ "$VERSION" =~ 11\.? ]] && return 0;
+  [[ "$VERSION" =~ 12\.? ]] && return 0;
+  [[ "$VERSION" =~ 13\.? ]] && return 0;
+  [[ "$VERSION" =~ 14\.? ]] && return 0;
+  [[ "$VERSION" =~ 15\.? ]] && return 0;
+  [[ "$VERSION" =~ 16\.? ]] && return 0;
+  [[ "$VERSION" =~ 17\.? ]] && return 0;
+  log "...this seems to be an old Java Runtime";
   JAVA_COMMAND=""
   return 1
 }
@@ -168,12 +181,6 @@ report_java_not_found() {
   log "JavaVM executable not found.
   You may want to set the path to the root of your Java Runtime installation
   in JAVA_HOME environment variable or pass it to ganttproject in --java-home argument";
-  if [ -z "$LOG_TEXT" ]; then
-    LOG_TEXT="$(cat /tmp/ganttproject-launcher.log)"
-  fi
-
-  LOG_TEXT=$(echo "$LOG_TEXT" | sed s/\"/\\\\\"/g)
-  echo "$LOG_TEXT"
 }
 
 # Create updates directory if not exists
@@ -182,15 +189,18 @@ mkdir -p "$USER_UPDATES_DIR"
 
 find_java
 
+if [ ! -f "$GP_HOME/eclipsito.jar" ]; then
+  log "Can't find the required Eclipsito library at $GP_HOME/eclipsito.jar"
+  exit 1
+fi
+CLASSPATH="$CLASSPATH:$GP_HOME/eclipsito.jar"
+export CLASSPATH
+BOOT_CLASS=com.bardsoftware.eclipsito.Launch
+
 log "JAVA_HOME=$JAVA_HOME"
 log "JAVA_COMMAND=$JAVA_COMMAND"
 log "GP_HOME=$GP_HOME"
 log "user.dir=$(pwd)"
-
-CLASSPATH="$CLASSPATH:$GP_HOME/eclipsito.jar"
-export CLASSPATH
-ECLIPSITO_ARGS="--verbosity 1 --version-dirs $GP_HOME/plugins:~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject"
-BOOT_CLASS=com.bardsoftware.eclipsito.Launch
 
 JAVA_EXPORTS="--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED\
   --add-exports javafx.base/com.sun.javafx=ALL-UNNAMED\
@@ -204,5 +214,4 @@ JAVA_EXPORTS="--add-exports javafx.controls/com.sun.javafx.scene.control.behavio
   --add-exports javafx.graphics/com.sun.javafx.util=ALL-UNNAMED\
   --add-opens java.desktop/sun.swing=ALL-UNNAMED\
   --add-opens java.desktop/sun.awt.X11=ALL-UNNAMED"
-JAVA_ARGS="-Xmx1024m $JAVA_EXPORTS -Duser.dir=$(pwd) $DEBUG_ARGS $BOOT_CLASS $ECLIPSITO_ARGS -log true -log_file $LOG_FILE"
-"$JAVA_COMMAND" $JAVA_ARGS "$@"
+"$JAVA_COMMAND" -Xmx1024m $JAVA_EXPORTS -Duser.dir="$(pwd)" $DEBUG_ARGS $BOOT_CLASS --version-dirs "$GP_HOME"/plugins:~/.ganttproject.d/updates -log true -log_file "$LOG_FILE" "${APP_ARGS[@]}"
