Run ganttproject with remote debugging

diff --git a/ganttproject-builder/ganttproject b/ganttproject-builder/ganttproject
--- a/ganttproject-builder/ganttproject
+++ b/ganttproject-builder/ganttproject
@@ -23,6 +23,35 @@ GP_HOME="$(pwd)"
 
 cd "$WORKING_DIR"
 
+PARSED_ARGS=$(getopt -o d:: --long debug:: -- "$@")
+eval set -- "$PARSED_ARGS"
+
+DEBUG_ARGS=""
+while true; do
+  case "$1" in
+    -d|--debug )
+      case "$2" in
+        "")
+          DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
+          shift 2
+          ;;
+        *)
+          DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,address=$2,suspend=n"
+          shift 2
+          ;;
+      esac
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo "Internal error!"
+      exit 1
+      ;;
+  esac
+done
+
 # Create log directory
 GP_LOG_DIR="$HOME/.ganttproject.d"
 # Check if log dir is present (or create it)
@@ -68,10 +97,9 @@ export CLASSPATH
 CONFIGURATION_FILE=ganttproject-eclipsito-config.xml
 BOOT_CLASS=org.bardsoftware.eclipsito.Boot
 
-JAVA_ARGS="-Xmx256m $BOOT_CLASS $CONFIGURATION_FILE -log -log_file $LOG_FILE"
+JAVA_ARGS="-Xmx256m $DEBUG_ARGS $BOOT_CLASS $CONFIGURATION_FILE -log -log_file $LOG_FILE"
 if [ -n "$(echo \"$*\" | sed -n '/\(^\|\s\)-/{p;}')" ]; then
   "$JAVA_COMMAND" $JAVA_ARGS "$@"
 else
   "$JAVA_COMMAND" $JAVA_ARGS "$@" &
 fi
-
