Try building mac distros with the signed libs

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -183,16 +183,14 @@ jobs:
                   echo "------------------ SIGNING ------------------------"                  
                   build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" sign build.keychain                  
                   jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject" --dest build/
-                  cd build
-                  for f in *.dmg; do
-                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
-                  done;
-                  cd ..
 
                   echo "------------------ NOTARIZING ------------------------"                  
                   build-bin/notarize.sh $VERSION "BarD Software s.r.o" "$MACOS_NOTARIZE_PASSWORD" notarize 
                   build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" staple
                   rm build/*.dmg
+                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject" --dest build/
+                  cd build
+                  mv ganttproject-1.0.dmg ganttproject-$VERSION-silicon.dmg
 
             - name: Upload artifacts
               run: |
@@ -202,68 +200,70 @@ jobs:
                     gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
                   done;
 
-#    macOS_intel:
-#        runs-on: macos-13
-#        steps:
-#            - uses: actions/checkout@v3
-#            - name: Checkout submodules
-#              shell: bash
-#              run: |
-#                  git submodule sync --recursive
-#                  git submodule update --init --force --recursive --depth=1
-#                  echo "$VERSION" > ganttproject-builder/VERSION
-#            - uses: actions/setup-java@v3
-#              with:
-#                  distribution: 'liberica'
-#                  java-version: 17.0.12
-#                  java-package: jdk+fx
-#                  cache: 'gradle'
-#            - name: Build GanttProject
-#              run: |
-#                  ./gradlew distbin
-#                  echo "===== PLUGINS ====="
-#                  ls ganttproject-builder/dist-bin/plugins/base
-#
-#            - name: Build GanttProject.app
-#              run: |
-#                  ./build-bin/package-mac.sh
-#                  ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to run"
-#
-#            - name: Sign GanttProject.app
-#              run: |
-#                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
-#
-#                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-#                  security default-keychain -s build.keychain
-#                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-#                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
-#                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-#
-#                  echo "------------------ NOW SIGNING ------------------------"
-#
-#                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" sign build.keychain
-#
-#                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject" --dest build/
-#                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "$MACOS_NOTARIZE_PASSWORD" notarize
-#                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" staple
-#                  rm build/*.dmg
-#                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject-notarized" --dest build/
-#
-#            - id: 'auth'
-#              uses: 'google-github-actions/auth@v1'
-#              with:
-#                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
-#
-#            - name: 'Set up Cloud SDK'
-#              uses: 'google-github-actions/setup-gcloud@v1'
-#
-#            - name: 'Use gcloud CLI'
-#              run: 'gcloud info'
-#
-#            - name: Upload artifacts
-#              run: |
-#                  #!/bin/sh
-#                  cd build
-#                  for f in *.dmg; do
-#                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
-#                  done;
+    macOS_intel:
+        runs-on: macos-13
+        steps:
+            - uses: actions/checkout@v3
+            - name: Checkout submodules
+              shell: bash
+              run: |
+                  git submodule sync --recursive
+                  git submodule update --init --force --recursive --depth=1
+                  echo "$VERSION" > ganttproject-builder/VERSION
+            - uses: actions/setup-java@v3
+              with:
+                  distribution: 'liberica'
+                  java-version: 17.0.12
+                  java-package: jdk+fx
+                  cache: 'gradle'
+            - name: Build GanttProject
+              run: |
+                  ./gradlew distbin
+                  echo "===== PLUGINS ====="
+                  ls ganttproject-builder/dist-bin/plugins/base
+
+            - name: Build GanttProject.app
+              run: |
+                  ./build-bin/package-mac.sh
+                  ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to run"
+
+            - name: Sign GanttProject.app
+              run: |
+                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
+
+                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+                  security default-keychain -s build.keychain
+                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
+                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+
+                  echo "------------------ NOW SIGNING ------------------------"
+
+                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" sign build.keychain
+
+                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject" --dest build/
+                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "$MACOS_NOTARIZE_PASSWORD" notarize
+                  build-bin/notarize.sh $VERSION "BarD Software s.r.o" "--" staple
+                  rm build/*.dmg
+                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject" --dest build/
+                  cd build
+                  mv ganttproject-1.0.dmg ganttproject-$VERSION-intel.dmg
+
+            - id: 'auth'
+              uses: 'google-github-actions/auth@v1'
+              with:
+                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+
+            - name: 'Set up Cloud SDK'
+              uses: 'google-github-actions/setup-gcloud@v1'
+
+            - name: 'Use gcloud CLI'
+              run: 'gcloud info'
+
+            - name: Upload artifacts
+              run: |
+                  #!/bin/sh
+                  cd build
+                  for f in *.dmg; do
+                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
+                  done;
